# make document

PutData = open("98765432011.txt", "w")

messageinput0 = ("------------------------------------------------------------------"+"\n")
messageinput1 = ("------------------Customer Information File-----------------------"+"\n")
messageinput2 = ("==> Account Number          : "+ "00000000011"+"\n")
messageinput3 = ("==> IFSC code               : "+ "RBIS0PFMS01"+"\n")
messageinput4 = ("==> Branch code             : "+ "PFMS01"+"\n")
messageinput5 = ("==> Account Type            : "+ "Saving type"+"\n")
messageinput6 = ("==> Customer Name           : "+ "MANAS KUMAR MISHRA"+"\n")
messageinput7 = ("==> D.O.B                   : "+ "23/JAN/2000"+"\n")
messageinput8 = ("==> Registered Phone Number : "+ "8384070561"+"\n")
messageinput9 = ("==> Email id                : "+ "esd18i011@iiitdm.ac.in"+"\n")
messageinput10 =("==> Marital Status          : "+ "Single"+"\n")
messageinput11 =("==> Current KYC Status      : "+ "Student in IIITDM kancheepuram"+"\n")
messageinput12 =("==> Address                 : "+ "Khajuri khas, New Delhi"+"\n")
messageinput13= ("------------------------------------------------------------------"+"\n")
messageinput14 =("------------------------------------------------------------------"+"\n")

PutData.write(messageinput0)
PutData.write(messageinput1)
PutData.write(messageinput2)
PutData.write(messageinput3)
PutData.write(messageinput4)
PutData.write(messageinput5)
PutData.write(messageinput6)
PutData.write(messageinput7)
PutData.write(messageinput8)
PutData.write(messageinput9)
PutData.write(messageinput10)
PutData.write(messageinput11)
PutData.write(messageinput12)
PutData.write(messageinput13)
PutData.write(messageinput14)

PutData.close()


PutData = open("98765432026.txt", "w")

messageinput0 = ("------------------------------------------------------------------"+"\n")
messageinput1 = ("------------------Customer Information File-----------------------"+"\n")
messageinput2 = ("==> Account Number          : "+ "00000000026"+"\n")
messageinput3 = ("==> IFSC code               : "+ "RBIS0PFMS01"+"\n")
messageinput4 = ("==> Branch code             : "+ "PFMS01"+"\n")
messageinput5 = ("==> Account Type            : "+ "Saving type"+"\n")
messageinput6 = ("==> Customer Name           : "+ "KARTHIKA RAJESH"+"\n")
messageinput7 = ("==> D.O.B                   : "+ "-------"+"\n")
messageinput8 = ("==> Registered Phone Number : "+ "9945726031"+"\n")
messageinput9 = ("==> Email id                : "+ "edm18b026@iiitdm.ac.in"+"\n")
messageinput10 =("==> Marital Status          : "+ "Single"+"\n")
messageinput11 =("==> Current KYC Status      : "+ "Student in IIITDM kancheepuram"+"\n")
messageinput12 =("==> Address                 : "+ "Bengaluru"+"\n")
messageinput13= ("------------------------------------------------------------------"+"\n")
messageinput14 =("------------------------------------------------------------------"+"\n")

PutData.write(messageinput0)
PutData.write(messageinput1)
PutData.write(messageinput2)
PutData.write(messageinput3)
PutData.write(messageinput4)
PutData.write(messageinput5)
PutData.write(messageinput6)
PutData.write(messageinput7)
PutData.write(messageinput8)
PutData.write(messageinput9)
PutData.write(messageinput10)
PutData.write(messageinput11)
PutData.write(messageinput12)
PutData.write(messageinput13)
PutData.write(messageinput14)

PutData.close()


PutData = open("98765432006.txt", "w")

messageinput0 = ("------------------------------------------------------------------"+"\n")
messageinput1 = ("------------------Customer Information File-----------------------"+"\n")
messageinput2 = ("==> Account Number          : "+ "00000000006"+"\n")
messageinput3 = ("==> IFSC code               : "+ "RBIS0PFMS01"+"\n")
messageinput4 = ("==> Branch code             : "+ "PFMS01"+"\n")
messageinput5 = ("==> Account Type            : "+ "Saving type"+"\n")
messageinput6 = ("==> Customer Name           : "+ "GANESH T S"+"\n")
messageinput7 = ("==> D.O.B                   : "+ "-------"+"\n")
messageinput8 = ("==> Registered Phone Number : "+ "8130983105"+"\n")
messageinput9 = ("==> Email id                : "+ "esd18i006@iiitdm.ac.in"+"\n")
messageinput10 =("==> Marital Status          : "+ "Single"+"\n")
messageinput11 =("==> Current KYC Status      : "+ "Student in IIITDM kancheepuram"+"\n")
messageinput12 =("==> Address                 : "+ "Bengaluru"+"\n")
messageinput13= ("------------------------------------------------------------------"+"\n")
messageinput14 =("------------------------------------------------------------------"+"\n")

PutData.write(messageinput0)
PutData.write(messageinput1)
PutData.write(messageinput2)
PutData.write(messageinput3)
PutData.write(messageinput4)
PutData.write(messageinput5)
PutData.write(messageinput6)
PutData.write(messageinput7)
PutData.write(messageinput8)
PutData.write(messageinput9)
PutData.write(messageinput10)
PutData.write(messageinput11)
PutData.write(messageinput12)
PutData.write(messageinput13)
PutData.write(messageinput14)

PutData.close()
